name: Push to Kaggle Dataset

on:
  push:
    branches:
      - master

env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.0.0

      - name: Upload
        run: python ${GITHUB_WORKSPACE}/ai4code/.github/workflows/sync_kaggle.py
