name: Push to Kaggle Dataset

on:
  release:
    types:
      - created

env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: tar
        run: tar -zcvf ai4code ai4code.tar.gz

      - name: prepare tarball
        run: |
          mkdir dataset
          tar -zcvf ai4code ai4code.tar.gz

      - name: upload
        uses: jaimevalero/push-kaggle-dataset@v3
        with:
          id: snaker/ai4code
          name: ai4code_source
          files: ai4code.tar.gz
          is_public: false
