name: Push to Kaggle Dataset

on:
  push:
    branches:
      - master

env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.7'

      - name: Upload
        run: |
          pip install --upgrade kaggle
          python ${GITHUB_WORKSPACE}/.github/workflows/sync_kaggle.py
