name: Push to Kaggle Dataset

on:
  push:
    branches:
      - master

env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: prepare tarball
        run: |
          tar -zcvf ai4code.tar.gz $GITHUB_WORKSPACE/ai4code

      - name: upload
        uses: jaimevalero/push-kaggle-dataset@v3
        with:
          id: snaker/ai4code
          name: ai4code_source
          files: ai4code.tar.gz
          is_public: false
